#!/usr/bin/env ruby

require 'json'

if ARGV.count != 3
  STDERR.puts "Usage: merge_infos_quorums_known <peer_infos> <quorums> <known_validators>"
  exit 1
end

peer_infos = JSON.load(File.read(ARGV[0]))
quorums = JSON.load(File.read(ARGV[1]))
known_validators = JSON.load(File.read(ARGV[2]))
seen_validators = {}

def iterate_validators(quorum, &block)
  quorum["validators"].each {|v| block[v] }
  quorum["inner_sets"].each {|qs| iterate_validators(qs, &block) }
end

def iterate_quorumsets(quorum, &block)
  block.call quorum["validators"]
  quorum["inner_sets"].each {|qs| iterate_quorumsets(qs, &block) }
end

def merge_quorumset(quorum, new_quorum)
  if quorum.empty?
    quorum.merge! new_quorum
    return
  end

  quorum["validators"] += new_quorum["validators"]
  quorum["validators"].uniq!

  quorum["inner_sets"] += new_quorum["inner_sets"] # TODO this is not correct
  quorum["inner_sets"].uniq!
end

quorums.each do |_, qss|
  qss.each do |qs|
    iterate_validators(qs) do |validator|
      seen_validators[validator] ||= { "peer_id" => validator }
    end
  end
end

peer_infos.each do |k,v|
  seen_validators[k] = v
end

quorums.each do |k, qss|
  seen_validators[k] ||= { "peer_id" => k} # this should not happen..
  seen_validators[k]["communicating_validators"] = qss.map{|qs| qs["owner"]}
end

known_validators.each do |k,v|
  seen_validators[k] ||= { "peer_id" => k} # this should not happen..
  seen_validators[k]["known_info"] = v
end

quorums.values.flatten.map do |qs|
  k = qs["owner"]
  seen_validators[k] ||= { "peer_id" => k} # this should not happen..
  quorum = seen_validators[k]["quorum"] ||= {}
  merge_quorumset(quorum, qs)
end
puts JSON.dump(seen_validators)
STDERR.puts "Seen #{seen_validators.count} validators"
